### ISSUE TITLE
Can't load blocks while using path MultiMC\libraries\com\mojang\minecraft, minecraft version:1.16.4

### ISSUE THREAD

**Issue by AC5174765920** [EwoutVDC/MCPixelArtConverter#2]
It just says "exception while loading minecraft.jar:object reference not set to an instance or an object."

**Comment by EwoutVDC** [comment]
Thanks for reporting your issue.
I managed to reproduce it on an old pc that still had the project. Setting it up on a new pc with new visual studio community was giving issues.

Seems like 1.16 changed something to the references naming again, sometimes adding "minecraft:" in front of the reference.
I will try to fix this if it is not too hard. I don't have much time to spend on this at the moment unfortunately

**Comment by EwoutVDC** [comment]
Should be fixed in the new release by commit 50cdeaf4299dbc111c2c6a5ba50f8789561992f9
